const d = [
  {
    title: "Cook reads",
    slug: "cookreads",
    desc: "blog about food. It provides recipes and information on healthy living.",
    image: "img/cookreads.png",
    cat: 1,
  },
  {
    title: "MERN Shop",
    slug: "MERN-shop",
    desc: "E-Commerce shop using MERN Stack",
    image: "img/MERN-shop.png",
  },
  {
    title: "MDweb",
    slug: "MDweb",
    desc: "Video ADs",
    image: "img/videos.png",
    cat: 1,
  },
  {
    title: "MERN Ecom",
    slug: "MERN-Ecom",
    desc: "MERN Ecommerce app",
    image: "img/mern-ecommerce.png",
  },
  {
    title: "MD Store",
    slug: "MD-Store",
    desc: "Store for Home and Decor",
    image: "img/mdstore.jpg",
    cat: 1,
  },
  {
    title: "ACI Adhesives",
    slug: "md-store",
    desc: "ACI :: Adhesives & Sealants :: Advanced Chemical Industries",
    image: "img/aci.jpg",
    cat: 1,
  },
  {
    title: "Alex West Egypt",
    slug: "alex-west",
    desc: "City Compound :: Villas :: Town House :: Quatro :: Hotel :: Golf",
    image: "img/alex-west.jpg",
    cat: 1,
  },
  {
    title: "United Cotton",
    slug: "United-Cotton",
    desc: "City Compound :: Villas :: Town House :: Quatro :: Hotel :: Golf",
    image: "img/United-Cotton.jpg",
    cat: 1,
  },
  {
    title: "CLT Shuttle",
    slug: "clt-shuttle",
    desc: "Airport Ground Transportation :: 24/7 USA",
    image: "img/cltshuttle.jpg",
    cat: 1,
  },
  {
    title: "Landing Page",
    slug: "Landing-Page",
    desc: "Simple landing page",
    image: "img/landing page.png",
  },
  {
    title: "Courses List",
    slug: "courses-list",
    desc: "Single page courses list",
    image: "img/react-courses-list.png",
  },
  {
    title: "My Reads",
    slug: "myreads",
    desc: "Simple Udacity Project ",
    image: "img/react myreads.jpg",
  },
  {
    title: "fyurr app",
    slug: "fyurr",
    desc: "Simple Udacity Project ",
    image: "img/fyyur.png",
  },
  {
    title: "Trivia API app",
    slug: "trivia-api",
    desc: "Simple Udacity Project ",
    image: "img/trivia_api.png",
  },
  {
    title: "TODO CRUD app",
    slug: "todo-crud",
    desc: "Simple Udacity Project ",
    image: "img/todo-crud.png",
  },
];
export default d;
